spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: gateway-service
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
