spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: candidat-service
#logging:
#  level:
#    org.apache.kafka: ERROR
#    org.apache.kafka.clients.NetworkClient: ERROR
