spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: "http://localhost:9098/realms/micro-service"
            token-uri: http://localhost:9098/realms/micro-service/protocol/openid-connect/token
            user-info-uri: http://localhost:9098/realms/micro-service/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

        registration:
          micro-service-api:
            client-id: micro-service-api
            client-secret: E3lXvxbU8Ebxoy71tvxdw1l7V778EYwW
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email
            provider: keycloak

      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-service"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: candidat-service
          uri: lb://CANDIDAT-SERVICE
          predicates:
            - Path=/api/v1/candidats/**
          filters:
            - StripPrefix=0
        - id: formateur-service
          uri: lb://FORMATEUR-SERVICE
          predicates:
            - Path=/api/v1/formateurs/**
          filters:
            - StripPrefix=0

        - id: cours-service-categories
          uri: lb://COURS-SERVICE
          predicates:
            - Path=/api/categories/**
          filters:
            - StripPrefix=0

        - id: cours-service-themes
          uri: lb://COURS-SERVICE
          predicates:
            - Path=/api/themes/**
          filters:
            - StripPrefix=0

keycloak:
  admin:
    url: http://localhost:9098
    realm: micro-service
    token-url: http://localhost:9098/realms/micro-service/protocol/openid-connect/token
    client-id: micro-service-api
    client-secret: E3lXvxbU8Ebxoy71tvxdw1l7V778EYwW

server:
  port: 8222
services:
  candidat:
    url: http://localhost:8090
  formateur:
    url: http://localhost:8083